version: '3.4'

services:
  directus:
    image: directus/directus:10

    volumes:
      - directus-uploads:/directus/uploads
      - directus-extensions:/directus/extensions
    networks:
      - directus-network
      - traefik-public
    tty: true
    stdin_open: true
    environment:
      KEY: '${UNIQUE_KEY}'
      SECRET: '${UNIQUE_SECRET}'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_POOL__MIN: '0'
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'
      # CACHE_AUTO_PURGE is for recreating the cache every time the db content is update/created/deleted - this will change in the future
      CACHE_AUTO_PURGE: 'true'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      PUBLIC_URL: 'https://${DIRECTUS_DOMAIN}'
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '8256'
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${PROJECT_NAME}-websecure.rule=Host(`${DIRECTUS_DOMAIN}`)"
        - "traefik.http.routers.${PROJECT_NAME}-websecure.tls.certresolver=letsencrypt"
        - "traefik.http.routers.${PROJECT_NAME}-websecure.entrypoints=websecure"
        - "traefik.http.routers.${PROJECT_NAME}-websecure.service=${PROJECT_NAME}-svc"
        - "traefik.http.services.${PROJECT_NAME}-svc.loadbalancer.server.port=8055"


  database:
    image: postgis/postgis:13-master
    tty: true
    stdin_open: true
    volumes:
      - directus-db:/var/lib/postgresql/data
    networks:
      - directus-network
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'


  cache:
    image: redis:6
    networks:
      - directus-network


volumes:
  directus-uploads:
  directus-extensions:
  directus-db:


networks:
  directus-network:
  traefik-public:
    external: true
