version: '3.4'

services:
  directus:
    image: directus/directus:10.8

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - directus-uploads:/directus/uploads
      #- directus-extensions:/directus/extensions
    networks:
      - directus-network
      - caddy-public

    tty: true
    stdin_open: true
    environment:
      KEY: '${UNIQUE_KEY}'
      SECRET: '${UNIQUE_SECRET}'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_POOL__MIN: '0'
      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'
      # CACHE_AUTO_PURGE is for recreating the cache every time the db content is update/created/deleted - this will change in the future
      CACHE_AUTO_PURGE: 'true'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${ADMIN_PASSWORD}'
      PUBLIC_URL: 'https://${DIRECTUS_DOMAIN}'
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '8256'
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "www.google.com google.com www.youtube.com youtube.com"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_ANCESTORS: "array:http://localhost:*,self"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}
      labels:
        caddy: ${DIRECTUS_DOMAIN}
        caddy.encode: zstd gzip
        caddy.encode.match.header: "!Content-Encoding"
        caddy.reverse_proxy: "{{upstreams 8055}}"


  database:
    image: postgis/postgis:13-master
    tty: true
    stdin_open: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - directus-db:/var/lib/postgresql/data
      - db-dumps:/db-dumps
    networks:
      - directus-network
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}


  cache:
    image: redis:6
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - directus-network


  filebrowser:
    image: hurlenko/filebrowser
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - directus-uploads:/data/directus/uploads
      #- directus-extensions:/data/directus/extensions
      - db-dumps:/data/directus/db-dumps
      - filebrowser-config:/config
    networks:
      - caddy-public
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints: 
          - ${NODE_PLACEMENT}
      labels:
        caddy: ${FILEBROWSER_DOMAIN}
        caddy.reverse_proxy: "{{upstreams 8080}}"


volumes:
  directus-uploads:
  #directus-extensions:
  directus-db:
  db-dumps:
  filebrowser-config:


networks:
  directus-network:
  caddy-public:
    external: true